### ISSUE TITLE
Extra function

### ISSUE THREAD

**Issue by shaan-hurley** [TannerYork/Spaceman#3]
https://github.com/TannerYork/Spaceman/blob/19c3c493c2a2ad39708f249b762ccf8a974cf413/spaceman.py#L17

You don't need a separate word list function, you can add all of this code to the load word function. Doing so well give you more concise code.

**Comment by TannerYork** [comment]
Your right, I don't need that function. I believe I added it when I was making a way to only read the list once, instead of every time a new word is needed and just remade the other function for no reson
