### ISSUE TITLE
Should use while loop

### ISSUE THREAD

**Issue by shaan-hurley** [TannerYork/Spaceman#5]
https://github.com/TannerYork/Spaceman/blob/19c3c493c2a2ad39708f249b762ccf8a974cf413/spaceman.py#L173

This code will only execute once. If the user wants to play a 3rd time it won't work

**Comment by TannerYork** [comment]
Actually, that if-statement is in the loop that continuously runs until the condition is false so it runs every time because it doesn't set the while condition to false.
